on: [push, pull_request, workflow_dispatch]

name: Build
jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 17
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - name: Install dependencies
        run: npm install
      - name: Generate unrouted PCBs
        run: |
          cp extra/index.js ./node_modules/ergogen/src/footprints
          cp extra/bat.js ./node_modules/ergogen/src/footprints
          cp extra/b3u1000p.js ./node_modules/ergogen/src/footprints
          cp extra/promicro.js ./node_modules/ergogen/src/footprints
          cp extra/pcm12.js ./node_modules/ergogen/src/footprints
          cp extra/promicro_pretty.js ./node_modules/ergogen/src/footprints
          npm run gen
      - name: Export DSN for main PCB
        uses: ./.github/actions/export-dsn
        with:
          pcb_file: output/pcbs/board.kicad_pcb
          dsn_file: output/pcbs/board.dsn
      - name: Autoroute main PCB
        uses: ./.github/actions/autoroute
        with:
          dsn_file: output/pcbs/board.dsn
          ses_file: output/pcbs/board.ses
      - name: Import SES into main PCB
        uses: ./.github/actions/import-ses
        with:
          pcb_input_file: output/pcbs/board.kicad_pcb
          pcb_output_file: output/pcbs/board_routed.kicad_pcb
          ses_file: output/pcbs/board.ses
      - name: Export Gerbers for top plate
        uses: ./.github/actions/export-gerbers
        with:
          pcb_file: output/pcbs/top_plate.kicad_pcb
          gerbers_dir: output/gerbers/top_plate
      - name: Export Gerbers for bottom plate
        uses: ./.github/actions/export-gerbers
        with:
          pcb_file: output/pcbs/bottom_plate.kicad_pcb
          gerbers_dir: output/gerbers/bottom_plate
      - name: Export Gerbers for main PCB
        uses: ./.github/actions/export-gerbers
        with:
          pcb_file: output/pcbs/board.kicad_pcb
          gerbers_dir: output/gerbers/board
      - name: Generate Images
        uses: ./.github/actions/export_pngs
        with:
          pcb_file: '"./output/pcbs/board.kicad_pcb"'
          pngs_dir: ./images
      - name: Update gallery
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: "Update gallery (automated)"
          commit_user_name: GitHub Actions Bot
          file_pattern: "**/*.png"
      - name: Persist output
        uses: actions/upload-artifact@v2
        with:
          name: samoklava-routed-pcbs-and-gerbers
          path: output
